scr/product/urls.py
from django.urls import path
from . import views 
from django.views.i18n import set_language



app_name ='products'


urlpatterns = [
    path('', views.product_list),
    path('<slug:slug>', views.product_detail , name='product_detail'),
    path('add_product/',views.add_product, name='add_product'),
    path('i18n/', set_language, name='set_language'),

] 

scr/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('product.urls',namespace='products')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include('accounts.urls',namespace='accounts')),



] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scr/product/models.py
from django.db import models
from django.utils.text import slugify

from django.utils.translation import gettext as _
# Create your models here.

    

class Product(models.Model):
    PRDName = models.CharField(max_length=100,verbose_name= _ ("product name"))
    PRDCategory = models.ForeignKey("Category", verbose_name= _("product category"), on_delete=models.CASCADE,null=True,blank=True)
    PRDVariant = models.ForeignKey("settings.Variant", verbose_name= _("product Variant"), on_delete=models.CASCADE,null=True,blank=True)
    PRDDesc = models.TextField(verbose_name= _("product description"))
    PRDImage =models.ImageField(upload_to = 'product_image',verbose_name= _("product images"),null=True,blank=True)
    PRDPrice = models.DecimalField(max_digits=5,decimal_places=2,verbose_name= _("price"))
    PRDDiscountprice = models.DecimalField(max_digits=5,decimal_places=2,verbose_name= _("discountprice"),null=True,blank=True)
    PRDCost = models.DecimalField( max_digits=5, decimal_places=2,verbose_name= _("cost"),null=True,blank=True)
    PRDCreated = models.DateTimeField(verbose_name= _("created at"),null=True,blank=True)
    PRDBrand = models.ForeignKey("settings.Brand", verbose_name= _("product brand"), on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.PRDName
    
    PRDSlug = models.SlugField(unique=True,blank=True)
    def save(self, *args, **kwargs):
        if not self.PRDSlug:
            self.PRDSlug = slugify(self.PRDName)
        super(Product, self).save(*args, **kwargs)
        

    
class ProductImage (models.Model):
    PRDIProduct = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name= _("product"))
    PRDIImage = models.ImageField(upload_to = 'product_image',verbose_name= _("product images"))

    def __str__(self):
        return str(self.PRDIProduct)
    
    
class Category(models.Model):
    CATName = models.CharField(verbose_name= _("product category"), max_length=50)
    CATParent = models.ForeignKey('self', verbose_name= _("parent"),limit_choices_to={'CATParent__isnull':True}, on_delete=models.CASCADE,null=True,blank=True)
    CATDesc = models.TextField()
    CATImg = models.ImageField(verbose_name= _("image"), upload_to='category')

    def __str__(self):
        return str(self.CATName)



class Product_Alternative(models.Model):

    PALTProduct = models.ForeignKey(Product,verbose_name=("Product"),related_name='main_product',on_delete=models.CASCADE)
    PALTAlternative = models.ManyToManyField(Product, verbose_name=("Product Alternativ"),related_name='Prodzuct_Alternativ')



    def __str__(self):
        return str(self.PALTProduct)


class Product_Accessories(models.Model):
    
    PACSProduct = models.ForeignKey(Product,verbose_name=("Product"),related_name='main_accproduct',on_delete=models.CASCADE)
    PACSAccessories = models.ManyToManyField(Product, verbose_name=("Product Accessories"),related_name='Product_Accessories')

    


    def __str__(self):
        return str(self.PACSProduct)

scr/product/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
          'PRDName', 
          'PRDCategory', 
          'PRDVariant',
          'PRDDesc',
          'PRDImage', 
          'PRDPrice',
          'PRDDiscountprice', 
          'PRDCost',
          'PRDCreated',
          'PRDBrand',
          'PRDSlug',
          ]
    # You can also add custom validation methods if needed
        widgets = {
            'PRDName':forms.TextInput(attrs={'class':'form-control',}) ,
            'PRDCategory':forms.Select(attrs={'class':'form-control'})  ,
            'PRDVariant':forms.Select(attrs={'class':'form-control'})  ,
            'PRDDesc':forms.TextInput(attrs={'class':'form-control'}) ,
            'PRDImage': forms.FileInput(attrs={'class': 'form-control','required':False}),
            'PRDPrice': forms.NumberInput(attrs={'class':'form-control'}), 
            'PRDDiscountprice':forms.NumberInput(attrs={'class':'form-control','required':False}), 
            'PRDCost':forms.NumberInput(attrs={'class':'form-control','required':False}),
            'PRDCreated': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}) ,
            'PRDBrand':forms.Select(attrs={'class': 'form-control'}),
            'PRDSlug':forms.TextInput(attrs={'class':'form-control'}) ,
          }
  

scr/product/views.py
from django.shortcuts import render,get_object_or_404,redirect

from django.http import HttpResponse
from django.utils.translation import activate
from .models import Product
from django.core.paginator import Paginator
from .forms import ProductForm
from django.urls import reverse




def add_product(request):
    product_list = Product.objects.all()

    if request.method == 'POST':
        add_book = ProductForm(request.POST,request.FILES)
        if add_book.is_valid():
            add_book.save()
            return redirect('product_list')

    context = {
        'form': ProductForm(),
    }
    return render(request, 'Product/add_product.html', context)


def product_list(request):
    product_list = Product.objects.all()

    paginator = Paginator(product_list, 3)  
    page_number = request.GET.get("page")
    product_list = paginator.get_page(page_number)
    
    context = {
    'product_list':product_list,
    'form' : ProductForm(),
    }
    
    return render(request,'Product/product_list.html' , context)



def product_detail(request , slug):

    product_detail = Product.objects.get(PRDSlug=slug)
    

    context = {'product_detail':product_detail}
    

    return render(request,'Product/product_detail.html' , context)



def my_view(request):
    # Determine user language preference or use site default
    user_language = request.LANGUAGE_CODE
    activate(user_language)
    # Your view logic here

scr/product/templates/Product/add_product.html
{% extends 'base.html' %} 
{% load static %}


{% block body %}
<div class= "m-5 py-5">
  <h1> add product </h1>
  <hr>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <br>
    <button type="submit">Submit</button> 
  </form>
</div>

{% endblock body %}

scr/product/templates/Product/product_detail.html
{%extends 'base.html'%}
{% load static %}

{% block body %}
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->

            <div class="col-md-6 mb-4 ">
                {% if product_detail.PRDImage %}
                    <img src="{{product_detail.PRDImage.url}}"
                        class="img-fluid"  />
                {% else %} 
                    <img src="{% static 'site_static/img/download.png' %}"
                        class="img-fluid"  /> 
                {% endif %}
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        
                            {% if product_detail.PRDDiscountprice > 0 %}
                                <a href="">
                                    <span class="badge bg-success me-1">Sale</span>
                                </a>
                            {% else %}
                                <a href="">
                                    <span class="badge bg-dark me-1">Category 2</span>
                                </a>
                            {% endif %}
                        <a href="">
                            <span class="badge bg-info me-1">New</span>
                        </a>
                        <a href="">
                            <span class="badge bg-danger me-1">Bestseller</span>
                        </a>
                    </div>

                    <strong><p style="font-size: 20px;">{{product_detail}}</p></strong>


                    {% if product_detail.PRDDiscountprice > 0 %}
                        <p class="lead">
                            <span class="me-1">
                                <del>${{product_detail.PRDPrice}}</del>
                            </span>
                            <span>${{product_detail.PRDDiscountprice}}</span>
                    {% else %}
                            <span>${{product_detail.PRDPrice}}</span>
                    {% endif %}
                        </p>


                    <strong><p style="font-size: 20px;">Description</p></strong>

                    <p> {{product_detail.PRDDesc}}.</p>

                    <form class="d-flex justify-content-left">
                        <!-- Default input -->
                        <div class="form-outline me-1" style="width: 100px;">
                            <input type="number" value="1" class="form-control" />
                        </div>
                        <button class="btn btn-primary ms-1" type="submit">
                            Add to cart
                            <i class="fas fa-shopping-cart ms-1"></i>
                        </button>
                    </form>
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-md-6 text-center">
                <h4 class="my-4 h4">Accessories</h4></div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->


{% endblock body %}

scr/product/templates/Product/product_list.html
{% extends 'base.html' %} 
{% load static %}


{% block body %}
<!--Main layout-->
<main class ="mt-5">
  <div class="container mt-5">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2 mt-5" style="background-color: #607D8B">
      <!-- Container wrapper -->
      <div class="container-fluid mt-2">
    
        <!-- Navbar brand -->
        <a class="navbar-brand pt-2" href="#">Categories:</a>
    
        <!-- Toggle button -->
        <button 
          class="navbar-toggler" 
          type="button" 
          data-mdb-toggle="collapse" 
          data-mdb-target="#navbarSupportedContent2" 
          aria-controls="navbarSupportedContent2" 
          aria-expanded="false" 
          aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
    
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse " id="navbarSupportedContent2" style ="margin-top: 10px;">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    
            <!-- Link -->
            <li class="nav-item acitve">
              <a class="nav-link text-white" href="#">All</a>
            </li>
            <li class="nav-item">
                  <a class="nav-link text-white" href="#">Shirts</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="#">Sport wears</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="#">Outwears</a>
                </li>
    
          </ul>
    
          <!-- Search -->
          <form class="w-auto py-1" style="max-width: 12rem">
            <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
          </form>
    
        </div>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
      
    <!-- Products -->
      <section>
      <div class="text-center">
        <div class="row">
          {% for product in product_list %}
          <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
              <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                data-mdb-ripple-color="light">
                {% if product.PRDImage %}
                  <img src="{{product.PRDImage.url}}"
                    class="w-100 "style = "height:200px;" />
                {% else %} 
                  <img src="{% static 'site_static/img/download.png' %}"
                    class="w-100 "style = "height:200px;" /> 
                {% endif %}
                <a href="#!">
                  <div class="mask">
                    <div class="d-flex justify-content-start align-items-end h-100">
                      <h5><span class="badge bg-dark ms-2">NEW</span></h5>
                    </div>
                  </div>
                  <div class="hover-overlay">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                  </div>
                </a>
              </div>
              <div class="card-body">
                <a href=" {% url 'products:product_detail' product.PRDSlug %}" class="text-reset">
                  <h5 class="card-title mb-2">{{product.PRDName}}</h5>
                </a>
                <a href="" class="text-reset ">
                  <p>{{product.PRDCategory}}</p>
                </a>
                <h6 class="mb-3 price">{{product.PRDPrice}}$</h6>
              </div>
            </div>
          </div>
          {% endfor %}
    
      </div>
    </section>
      
    <!-- Pagination -->
    <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
      <ul class="pagination">
        <span class="step-links">
          {% if product_list.has_previous %}
            <li class="d-inline">
              <a href="?page=1">&laquo; first</a>
            </li>
            <li class="d-inline">
              <a href="?page={{ product_list.previous_page_number }}">&lsaquo; prev</a>
            </li>
          {% endif %}
    
          {% for i in product_list.paginator.page_range %}
            <li class="d-inline {% if product_list.number == i %}current{% endif %}">
              <a href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endfor %}
    
          {% if product_list.has_next %}
            <li class="d-inline">
              <a href="?page={{ product_list.next_page_number }}">next &rsaquo;</a>
            </li>
            <li class="d-inline">
              <a href="?page={{ product_list.paginator.num_pages }}">last &raquo;</a>
            </li>
          {% endif %}
        </span>
      </ul>
    </nav>


    <!-- Pagination -->


    <div class="container mt-5">
      <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
              Dropdown Button
          </button>
      </div>
    </div>

  


  
  
  </main>
  <!--Main layout-->





{% endblock body %}